sudo: requird
services:   
  - docker
env:
    global: 
      - SHA=$(git rev-parse HEAD)
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9087f13b972f_key -iv $encrypted_9087f13b972f_iv -in posts-k8s-1367c174c940.json.enc -out posts-k8s-1367c174c940.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file posts-k8s-1367c174c940.json
  - gcloud config set project posts-k8s
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kdsofts/Posts-app -f ./client/Dockerfile.dev ./client
script:
  - docker run parthkd/Posts-app npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: main